Noun1 = input("please entera noun ")
Noun2 = input("please enter a noun ")
Noun3 = input("please enter a noun ")
Adjective1 = input("please enter a adjective ")
Adjective2 = input("please enter a adjective ")
verb1 = input("please enter a adjective ")
Noun4 = input("please enter a noun ")
Adjective3 = input("please enter a adjective ")
misc1 = input("please enter misc ")
Noun5 = input("please enter a noun ")
misc2 = input("please enter misc ")
Noun6 = input("please enter a noun ")
Adjective4 = input("please enter a adjective ")
Noun7 = input("please enter a noun ")
verb2 = input("please enter a verb ")
print("Every Halloween my " + Noun1 + " and i head for the local haunted " + Noun2 + "but we always " + Noun3 + "out! This year we decided to be " + Adjective1 + "and make the trip. When we got there we heard0" + Adjective2 + " noises and found other kids " + verb1 + " inside we could/'t see a " + Noun4 + " because it was so dark! but slowly we started seeing " + Adjective3 + " things! There but slowly we started seeing " + misc1 + " everywhere and when we turned a corner a " + Noun5 + " would jump out! Just when we were the most scared one of the " + misc2 + " tripped and fell right in front of us-and its one of the " + Noun6 + " flew off! We started laughing and after that nothing seemed as " + Adjective4 + " From now on I won/'t be able to see a " + Noun7 + " without " + verb2 + "! ")
