#Made By John
month1 = input("please input a month ")
adjective1 = input("please input a adjective ")
food1 = input("please unput a food ")
verb1 = input("please input a verb ")
verb_past_tense1 = input("please input a verb in past tense ")
plural_noun1 = input("please input a plural noun ")
plural_noun2 = input("please input a plural noun ")
verb_past_tense2 = input("please input a verb in past tense ")
plural_noun3 = input("please input a plural noun ")
verb2 = input("please input a verb ")
adjective2 = input("please input a adjective ")
plural_noun4 = input("please input a plural noun ")
plural_noun5 = input("please input a plural noun ")
verb3 = input("please input a verb ")
noun1 = input("please input a noun ")
verb4 = input("please input a verb ")
adjective3 = input("please input a adjective ")
adjective4 = input("please input a adjective")
noun2 = input("please input a noun ")
print(' Every ' + month1 + ' my family celebrates thanksgiving. First my parents buy a ' + adjective1 + food1 + ' to ' + verb1 + ' in the oven all day. For side dishes my family makes ' + verb_past_tense1 + plural_noun1 + plural_noun2 + ' and ' + verb_past_tense1 + plural_noun2 + ' I help ' + verb2 + ' the table with a ' + adjective2 + ' tablecloth decorated with ' + plural_noun3 + ' and ' +  plural_noun4 + ' The worst part is cleaning up; we ' + verb3 + ' The dishes in the ' +  noun1 + ' and have to ' + verb4 + ' them all in ' + adjective3 + ' water But at least ther\'s always ' + adjective4 + noun2 + ' for dessert!')
